export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL = "COMPLETE_ALL";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_RECEIVED = "PROFILE_RECEIVED";

export const GET_SHAREPOINT_DATA = "GET_SHAREPOINT_DATA";
export const GET_REST_SHAREPOINT_DATA = "GET_REST_SHAREPOINT_DATA";
export const GET_FRESH_SHAREPOINT_DATA = 'GET_FRESH_SHAREPOINT_DATA'

export const GET_SEARCHED_SHAREPOINT_DATA = "GET_SEARCHED_SHAREPOINT_DATA";
export const GET_USERSEARCHED_DATA = "GET_USERSEARCHED_DATA";

export const GET_GL_REPORT = "GET_GL_REPORT";

export const GET_CER_REPORT = "GET_CER_REPORT";

export const GET_CER_REPORT_FILTER = "GET_CER_REPORT_FILTER";

export const GET_MEDICALREPORT = "GET_MEDICALREPORT";

export const GET_COSTCENTER_REQUEST = 'GET_COSTCENTER_REQUEST';
export const UPDATE_ACKNOWLEDGEAPPS = 'UPDATE_ACKNOWLEDGEAPPS';
